# Generated by Django 2.0.3 on 2018-04-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Answer Options',
                'verbose_name': 'Answer Option',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Quizes',
                'verbose_name': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('correct', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='quiz_test.Answer_Options')),
                ('possible_answers', models.ManyToManyField(to='quiz_test.Answer_Options')),
                ('quiz', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_test.Quiz')),
                ('selected', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='quiz_test.Answer_Options')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'verbose_name': 'Quiz Question',
            },
        ),
        migrations.CreateModel(
            name='Turtles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turtle_type', models.CharField(max_length=40)),
                ('image_url', models.ImageField(upload_to='turtle_pics/')),
                ('locations', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=200)),
                ('diet', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Turtles',
                'verbose_name': 'Turtle',
            },
        ),
    ]
