# Generated by Django 2.0.3 on 2018-04-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turtles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turtle_type', models.CharField(max_length=40)),
                ('image_url', models.ImageField(upload_to='turtle_pics/')),
                ('locations', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('lifespan', models.CharField(max_length=200)),
                ('diet', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
