# Generated by Django 2.0.3 on 2018-04-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='correct',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='quiz_test.Answer_Options'),
        ),
        migrations.AlterField(
            model_name='quiz_question',
            name='selected',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected', to='quiz_test.Answer_Options'),
        ),
    ]
